# Generated by Django 5.2.7 on 2025-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_apellidos_usuario_nombres_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área/Unidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mfa_habilitado',
            field=models.BooleanField(default=False, verbose_name='MFA habilitado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Usuario', max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último acceso'),
        ),
    ]
