# Generated by Django 5.2.5 on 2025-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('ean_upc', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('uom_compra', models.CharField(max_length=20)),
                ('uom_venta', models.CharField(max_length=20)),
                ('factor_conversion', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19, max_digits=4)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perishable', models.BooleanField(default=False)),
                ('control_por_lote', models.BooleanField(default=False)),
                ('control_por_serie', models.BooleanField(default=False)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
