# Generated by Django 5.2.7 on 2025-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_ficha_tecnica_url_producto_punto_reorden_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoproveedor',
            name='descuento_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='min_lote',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_principal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_principal_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_principal_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='condiciones_pago',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedor',
            unique_together={('producto', 'proveedor')},
        ),
    ]
